rootProject.name = 'jetty-client-instrumentation'
include 'Jetty-Client-8'
include 'Jetty-Client-9'
include 'Jetty-Client-9.1.1'
include 'Jetty-Client-9.2.8'
include 'Jetty-Client-9.2.11'
include 'Jetty-Client-9.3.0'
include 'Jetty-Client-9.3.7'
include 'Jetty-Client-10.0'
include 'Jetty-Client-12.0'
