// Build.gradle generated for instrumentation module Jetty-Client-8

apply plugin: 'java'

dependencies {
    implementation 'org.eclipse.jetty:jetty-client:8.2.0.v20160908'
    // New Relic Java Agent dependencies
    implementation 'com.newrelic.agent.java:newrelic-agent:' + project.findProperty('java.agent.version')
    implementation 'com.newrelic.agent.java:newrelic-api:' + project.findProperty('java.agent.version')
    implementation 'com.newrelic.agent.java:agent-bridge:' + project.findProperty('java.agent.version')
    implementation fileTree(include: ['*.jar'], dir: '../test-lib')
}

jar {
    manifest {
        attributes 'Implementation-Title': 'com.newrelic.instrumentation.labs.Jetty-Client-8'
        attributes 'Implementation-Vendor': 'New Relic Labs'
        attributes 'Implementation-Vendor-Id': 'com.newrelic.labs'
        attributes 'Implementation-Version': 1.0
    }
}

verifyInstrumentation {
    passesOnly 'org.eclipse.jetty:jetty-client:[7.5.0.v20110901,9.0.0)'
    excludeRegex '.*M.*'
    excludeRegex '.*Beta.*'
    excludeRegex '.*RC.*'
    excludeRegex '.*SNAPSHOT.*'
}
